apiVersion: apps/v1
kind: Deployment
metadata:
  name: abstergo-deployment
  labels:
    app: abstergo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: abstergo
  template:
    metadata:
      labels:
        app: abstergo
    spec:
      containers:
        - name: abstergo-container
          image: mmaaroju/abstergo-portal:latest
          ports:
            - containerPort: 8081
          livenessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 15
            timeoutSeconds: 1
            periodSeconds: 10
        resources:
          requests:
            cpu: 200m
